package jsonldkeywords

const (
	Base      = "@base"
	Container = "@container"
	Context   = "@context"
	Direction = "@direction"
	Graph     = "@graph"
	Id        = "@id"
	Import    = "@import"
	Included  = "@included"
	Index     = "@index"
	JSON      = "@json"
	Language  = "@language"
	List      = "@list"
	Nest      = "@nest"
	None      = "@none"
	Prefix    = "@prefix"
	Propagate = "@propagate"
	Protected = "@protected"
	Reverse   = "@reverse"
	Set       = "@set"
	Type      = "@type"
	Value     = "@value"
	Version   = "@version"
	Vocab     = "@vocab"
)
